permalink: /:title

title: Xiangmin(Shannon) 
url: https://github.com/xhan-shannon
feed: /atom.xml
author_info: <a href="https://github.com/xhan-shannon">Xiangmin(Shannon)</a>

theme: jekyll-theme-cayman
